Feature/pharmacist model
DAWAYA-ORG/Dawaya-backend pull request #7
Opened 2024-09-14 20:56 UTC by muhammad-nabih

2024-09-16 22:29 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +        maxLength: 50
image : {
            type: String,
            default: 'default.jpg',
        },

2024-09-16 22:29 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +        minLength: [6, 'Password must be at least 6 characters long']
add in password: select: false,

2024-09-16 22:29 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +    },
passwordConfirm: {
            type: String,
            required: [true, 'Please confirm your password'],
            validate: {
                validator: function (el) {
                    return el === this.password;
                },
                message: 'Password are not the same!',
            },
        },

2024-09-16 22:29 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +pharmacistSchema.index({ licenseNumber: 1, email: 1 });
مش مستاهله وبتقلل ال performance: index

2024-09-16 22:29 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +    role: {
role: in the top (first)

role: {
            type: String,
            default: 'pharmacist'
        }

2024-09-16 22:29 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +    createdBy: {
createdBy: delete it

2024-09-16 22:29 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +        ref: "inventory",
Inventory : capital I

2024-09-16 22:29 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +        required: true
isBlocked:{
        type:Boolean,
        default: false,
    },

2024-09-16 22:29 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +    email: {
validate with npm package 

validate: [validator.isEmail, 'Please provide a valid email'],
https://www.npmjs.com/package/validator

2024-09-17 02:12 UTC, muhammad-nabih commented on database/models/pharmacist.model.ts
> +pharmacistSchema.index({ licenseNumber: 1, email: 1 });
after all this I think a new pull request should be submitted What are all these comments?

2024-09-17 03:06 UTC, muhammad-nabih commented
**Please Review My code Again**

2024-09-17 17:09 UTC, mennaseif requested changes

2024-09-17 17:09 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +    inventories: {
Inventory onlyyyyyyyyyyyyyyyyyyyyyyyy without sssssssssssssssssssssssssss

2024-09-17 17:43 UTC, mennaseif requested changes

2024-09-17 17:43 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +      trim: true,
delete trim

2024-09-17 17:57 UTC, mennaseif requested changes

2024-09-17 17:57 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +    },
add imageUrl:{
type:string
default:"default.jpg"
}

2024-09-17 21:39 UTC, mennaseif requested changes

2024-09-17 21:39 UTC, mennaseif commented on database/models/pharmacist.model.ts
> +      trim: true,
!!!

2024-09-17 22:40 UTC, muhammad-nabih commented on database/models/pharmacist.model.ts
> +    inventories: {
okaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaay

2024-09-17 22:42 UTC, muhammad-nabih commented on database/models/pharmacist.model.ts
> +    },
done

2024-09-17 22:44 UTC, mennaseif approved these changes

2024-09-17 22:45 UTC, merged